### ISSUE TITLE
Non friends have all the permissions in my plot

### ISSUE THREAD

**Issue by Filocava99** [ImMorpheus/Metropolis#27]
Non friends have all the permissions in my plot

**Comment by ImMorpheus** [comment]
I'll need a lot more than this. Either they have a "stronger" rank or you changed your plot's permissions.

**Comment by Filocava99** [comment]
https://prnt.sc/rtgiya
A player with citizen rank is opening inventories(https://prnt.sc/rtgjc6) in my plot (https://prnt.sc/rtgiya). The plot perm list are (https://prnt.sc/rtgj49).
I don't have any friend https://prnt.sc/rtgl77

**Comment by ImMorpheus** [comment]
`Interact Block` allows them to open inventories, assuming `C` means `Citizen`.

I'll look into splitting interact_inventory from interact_block

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/ImMorpheus/Metropolis/commit/f33cea6223f3aa665c07d45f4f3751aef3951f38
