### ISSUE TITLE
Can't breed animals in claimed plots

### ISSUE THREAD

**Issue by Rysaen** [ImMorpheus/Metropolis#31]
**Describe the bug**
Can't breed animals in claimed plots. Tested with the following entities:

- Cow
- Pig
- Chicken

Steps to reproduce the behavior are self-explanatory. Just try to breed any of these animals in claimed plots. This bug seems to be introduced in 3a41c4d6177a4af37929e7ed778537361435237a. Could be related to: https://github.com/ImMorpheus/Metropolis/blob/3818c58c743f47f8e5f9d86bb4563f8cf890822a/src/main/java/me/morpheus/metropolis/listeners/InteractTownHandler.java#L133-L136.

**Expected behavior**
Should be able to breed animals.

**I am currently running**
- Sponge version: 7.2.0
- Metropolis version: any build from f33cea6223f3aa665c07d45f4f3751aef3951f38 to 3a41c4d6177a4af37929e7ed778537361435237a (included)
- Plugins: Metropolis-0.0.1, TotalEconomy-1.8.1
- Mods: -

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/ImMorpheus/Metropolis/commit/7e9d402369b91541081d22f8eccd764cfd2c4426
