### ISSUE TITLE
Reset plot command

### ISSUE THREAD

**Issue by Filocava99** [ImMorpheus/Metropolis#33]
It would be very useful to have a command that resets the plot. With reset I mean:

- remove any owner
- set the default permissions

**Comment by ImMorpheus** [comment]
Added by https://github.com/ImMorpheus/Metropolis/commit/650b66f6c5f2ffbc922d128ceca6f4899c36b7f5 and https://github.com/ImMorpheus/Metropolis/commit/00fc5f05d05c44765b62db142aaa2e7ce6db5ad0
