### ISSUE TITLE
Plot perms/owners bugged

### ISSUE THREAD

**Issue by Filocava99** [ImMorpheus/Metropolis#35]
**Describe the bug**
Every time a plot owner logoff, he lost the ownership of the plot. Sometimes an assistant can't interact with an inventory even if the perms allow him to do that.
When a city is close to the claims limit, the mayor can't claim anymore. For example, I have players that had a town with 33 of 50 plot and they couldn't claim anymore.

**Expected behavior**
You should keep the ownership after the server restart or the player logout
You should be able to interact with everything in every plot if you are an assistant or mayor
You should be able to claim new plot if you haven't reached the plot limit

**Comment by ImMorpheus** [comment]
Don't report diffrent bugs in the same issue.
