### ISSUE TITLE
Plot owner lost on server restart

### ISSUE THREAD

**Issue by kaotich00** [ImMorpheus/Metropolis#37]
**Describe the bug**
Users have reported a recurrent behaviuour: every time the server is restarted every plot loses the owner and must be reassigned.

**Expected behavior**
The plot owner must persist after server restart.

**I am currently running**
- Sponge version: 7.2.0
- Metropolis version: 0ec5457ae72a0a377df99832aed43481d1ac4b8a

**Comment by ImMorpheus** [comment]
Sponge issue: https://github.com/SpongePowered/SpongeCommon/pull/2575
